### ISSUE TITLE
CSS Bindings v2

### ISSUE THREAD

**Issue by elving** [beatgig/synth#10]
Currently, Synth CSS bindings only support transforming numeric token values into pixels units. We need to be able to support relative length units, specially `em` and `rem` conversion from `px` units as well as other output formats (e.g., object notation).

## Current API

```javascript
fontSize({
  typography: {
    size: {
      base: 16,
      menu_link: 14,
  },
}, 'menu_link') // => font-size: 14px;
```

## Future API

```javascript
const fs = fontSize({
  typography: {
    size: {
      base: 16,
      menu_link: 14,
  },
}, 'menu_link')

console.log(fs) // => font-size: 14px;
console.log(fs.toRem()) // => font-size: 0.875rem;
console.log(fs.toJSON()) // => { fontSize: '0.875rem' }
```

## Tasks

- [ ] Add support for `px` unit conversion into `rem` and `em` units.
- [ ] Add support for object notation format.
- [ ] Update `synth-ui` components to use relative units (`rem` for text  and `em` for everything else).
