### ISSUE TITLE
Token Configuration v2

### ISSUE THREAD

**Issue by elving** [beatgig/synth#7]
The token configuration is the single source of truth for your design system, so it's crucial that we facilitate the ability to describe the tokens along side their values. To do so, we have to change the way in which we define the values so that we can also define metadata alongside the actual token value.

## Current API

```javascript
const tokens = {
  color: {
    background: {
      base: "#f4f4f4",

      button: {
        default: "#464159",
        hover: "#6c7b95"
      },

      popup: "#d9dad7"
    }
  }
};
```

## Future API

```javascript
const tokens = {
  color: {
    background: {
      base: {
        release: '1.0.2',
        value: '#f4f4f4',
      },

      button: {
        default: {
          description: 'The default background color for all basic buttons.',
          release: '1.2.0',
          value: '#464159',
        },

        hover: {
          description: 'The default background color used when hovering button all basic buttons.'
          value: '#6c7b95',
        }
      },

      popup: '#d9dad7',
    },
  },
}
```

In the future, we'll be able to add metadata to any token by using an object instead of a raw token value. This object has to contain a `value` key that will have the token's actual value. Every other key on the object will be treated as metadata. These metadata values can then be used when generating documentation for your tokens and the components consuming those tokens.

Passing a raw value (e.g. like in the `popup` token) would still be valid which is useful when prototyping and experimenting as it saves time when creating your tokens.

The metadata keys you define per token are up to you, which makes it possible to add any extra information you'd like on to your token configuration but the following metadata keys are taken into account by Synth in order to produce automatic token configuration documentation:

- `description`: used to provide a description of the token, e.g., usage, purpose, etc.
- `release`: used to document the release version in which the token was first introduced.

## Tasks

- [ ] Add support for metadata objects as token values.
- [ ] Revisit all `categories` and their `properties`.
- [ ] Add new category and properties related to transitions and animations.
- [ ] Update `synth-tokens` with new `categories` and `properties`.
