### ISSUE TITLE
Token Aliases v1

### ISSUE THREAD

**Issue by elving** [beatgig/synth#8]
Adding a `global` category proved useful for reusing common token values across multiple categories and properties but as whit anything global, it is prone to naming collisions and difficult to maintain. In order to provide the same solution but make it more manageable (specially at scale) we'll be introducing the concept of token aliases. A token alias is essentially a global token that is scoped to a specific category, which will:

- Help prevent the propensity of naming collisions by adding prefixes to aliases, i.e., `global:base` v.s. `color:aliases.base`.
- Help find the source of aliases specially when dealing with large token configurations. If you were to split the configuration into files pertaining to a specific category, e.g., `color.js` or `typography.js`, category scoped aliases will be present in the same file which would make them easier to find.

## Current API

```javascript
const tokens = {
  global: {
    content: "#f4f4f4"
  },

  color: {
    background: {
      base: "@content",

      button: {
        default: "#464159",
        hover: "#6c7b95"
      },

      popup: {
        value: "@content"
      }
    }
  }
};
```

## Future API

```javascript
const tokens = {
  color: {
    aliases: {
      content: {
        description: 'Default background color for containers.'
        value: '#f4f4f4',
      }
    },

    background: {
      base: {
        release: '1.0.2',
        value: '@content',
      },

      button: {
        default: {
          description: 'The default background color for all basic buttons.',
          release: '1.2.0',
          value: '#464159',
        },

        hover: {
          description: 'The default background color used when hovering button all basic buttons.'
          value: '#6c7b95',
        }
      },

      popup: '@content',
    },
  },
}
```

## Tasks

- [ ] Add support for the new `aliases` property.
- [ ] Update all documentation related to "global tokens".
- [ ] Update `synth-tokens` package to use the `aliases` property instead of the `global` category.
